fix: workflow, again (x2)

diff --git a/.github/workflows/validate.yml b/.github/workflows/validate.yml
--- a/.github/workflows/validate.yml
+++ b/.github/workflows/validate.yml
@@ -2,9 +2,9 @@ name: Validate
 
 on:
   push:
-    branches: [main]
+    branches: [ main ]
   pull_request:
-    branches: [main]
+    branches: [ main ]
 jobs:
   run:
     runs-on: ubuntu-latest
@@ -12,6 +12,9 @@ jobs:
       - uses: actions/checkout@v2
       - run: sudo apt-get install -y yara
       - run: |
-          output=$(find . -type f -iname "*.yara" -exec yara -w {} /dev/null \; 2>&1)
+          output=$(find . -type f -iname "*.yara" -exec yara -w {} \; 2>&1)
           echo "$output"
-          echo "$output" | grep -q 'syntax error' && { echo "error"; exit 1; }
+          if echo "$output" | grep -q 'syntax error'; then
+            echo "syntax error"
+            exit 1
+          fi
