fix: workflow, again

diff --git a/.github/workflows/validate.yml b/.github/workflows/validate.yml
--- a/.github/workflows/validate.yml
+++ b/.github/workflows/validate.yml
@@ -6,9 +6,12 @@ on:
   pull_request:
     branches: [main]
 jobs:
-  validate:
+  run:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
       - run: sudo apt-get install -y yara
-      - run: find . -type f -iname "*.yara" -exec yara -w {} /dev/null \; 2>&1 | tee /dev/stderr | grep -q 'error' && exit 1
+      - run: |
+          output=$(find . -type f -iname "*.yara" -exec yara -w {} /dev/null \; 2>&1)
+          echo "$output"
+          echo "$output" | grep -q 'syntax error' && { echo "error"; exit 1; }
